"""empty message

Revision ID: 5b5d3f1fa57d
Revises: d1ace6cef796
Create Date: 2023-07-10 10:54:05.464391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5d3f1fa57d'
down_revision = 'd1ace6cef796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookkeeping_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landing_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookkeeping_ticket', schema=None) as batch_op:
        batch_op.drop_column('landing_status')

    # ### end Alembic commands ###
