"""empty message

Revision ID: c9bba712842c
Revises: 
Create Date: 2023-05-16 10:22:55.234033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bba712842c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bussiness_plan',
    sa.Column('bussines_plan_id', sa.String(length=36), nullable=False),
    sa.Column('bussines_name', sa.String(length=255), nullable=True),
    sa.Column('bussines_email', sa.String(length=100), nullable=True),
    sa.Column('bussines_type', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('adress', sa.Text(), nullable=True),
    sa.Column('geolocation', sa.String(length=100), nullable=True),
    sa.Column('budgets', sa.Integer(), nullable=True),
    sa.Column('customer_age', sa.Integer(), nullable=True),
    sa.Column('target_market', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('bussines_plan_id')
    )
    op.create_table('money_bookeeping',
    sa.Column('money_bookeeping_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('balances', sa.Integer(), nullable=True),
    sa.Column('id_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('money_bookeeping_id')
    )
    op.create_table('postal_code_address',
    sa.Column('postal_code', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('postal_code')
    )
    op.create_table('provinces_list',
    sa.Column('province_id', sa.String(length=36), nullable=False),
    sa.Column('province_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('province_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('telephone_number', sa.String(length=15), nullable=True),
    sa.Column('postal_code', sa.String(length=36), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['postal_code'], ['postal_code_address.postal_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('regencys_list',
    sa.Column('regency_id', sa.String(length=36), nullable=False),
    sa.Column('regencys_name', sa.String(length=30), nullable=True),
    sa.Column('provincy_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['provincy_id'], ['provinces_list.province_id'], ),
    sa.PrimaryKeyConstraint('regency_id')
    )
    op.create_table('users_history',
    sa.Column('user_history', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('history_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_history')
    )
    op.create_table('subdistricts_list',
    sa.Column('subdistrict_id', sa.String(length=36), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=30), nullable=True),
    sa.Column('regencys_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['regencys_id'], ['regencys_list.regency_id'], ),
    sa.PrimaryKeyConstraint('subdistrict_id')
    )
    op.create_table('pivot_postel_code_location',
    sa.Column('postel_code_location', sa.String(length=36), nullable=False),
    sa.Column('provinces_id', sa.String(length=36), nullable=False),
    sa.Column('districts_id', sa.String(length=36), nullable=False),
    sa.Column('subdistricts_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['districts_id'], ['regencys_list.regency_id'], ),
    sa.ForeignKeyConstraint(['provinces_id'], ['provinces_list.province_id'], ),
    sa.ForeignKeyConstraint(['subdistricts_id'], ['subdistricts_list.subdistrict_id'], ),
    sa.PrimaryKeyConstraint('postel_code_location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pivot_postel_code_location')
    op.drop_table('subdistricts_list')
    op.drop_table('users_history')
    op.drop_table('regencys_list')
    op.drop_table('profile')
    op.drop_table('users')
    op.drop_table('provinces_list')
    op.drop_table('postal_code_address')
    op.drop_table('money_bookeeping')
    op.drop_table('bussiness_plan')
    # ### end Alembic commands ###
