"""empty message

Revision ID: d1ace6cef796
Revises: 65435c08ba1d
Create Date: 2023-07-10 10:25:47.599771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ace6cef796'
down_revision = '65435c08ba1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookkeeping_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bussiness_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bussiness_location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=12), nullable=True))
        batch_op.alter_column('name_account',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=72),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookkeeping_account', schema=None) as batch_op:
        batch_op.alter_column('name_account',
               existing_type=sa.String(length=72),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('postal_code')
        batch_op.drop_column('bussiness_location')
        batch_op.drop_column('bussiness_email')

    # ### end Alembic commands ###
