"""empty message

Revision ID: df5232e33c59
Revises: 6634628e71e3
Create Date: 2023-07-10 15:51:42.691851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5232e33c59'
down_revision = '6634628e71e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookkeeping_activity', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookkeeping_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
